build-site.jl

These changes were made automatically, please check before merging.

[AUTO] Change master to main

---

tutorials/introduction-to-adnlpmodels/Project.toml
tutorials/introduction-to-adnlpmodels/index.jmd

https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/issues/51

New tutorial: add ADNLPModels tutorial

---

tutorials/introduction-to-nlpmodelsjump/index.jmd

I fixed https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/pull/19 in https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/pull/20 , but the last merge didn't trigger the deployment. So, this is an attempt

Try trigger deploy

---

tutorials/introduction-to-optimizationproblems/Project.toml
tutorials/introduction-to-optimizationproblems/index.jmd

https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/issues/51

Add OptimizationProblems tutorial

---

tutorials/introduction-to-nlpmodelsipopt/Project.toml
tutorials/introduction-to-nlpmodelsipopt/index.jmd

https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/issues/51

add NLPModelsIpopt tutorial

---

tutorials/introduction-to-nlpmodelsipopt/index.jmd

Debug https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/pull/85#issuecomment-1213181596
and include @dpo 's suggesiton in https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/pull/28

Debug nlpmodelsipopt tutorial

---

tutorials/introduction-to-cannoles/Project.toml
tutorials/introduction-to-cannoles/index.jmd

https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/issues/51

Add CaNNOLeS tutorial

---

.github/workflows/Deploy-internal.yml
.github/workflows/Deploy-website.yml

Build the preview and push to gh-pages.
Ref:
- #30

Build preview and push to gh-pages

---

tutorials/using-callbacks/Project.toml
tutorials/using-callbacks/index.jmd

New tutorial: Using callbacks

---

tutorials/using-callbacks/index.jmd

Use global inside using-callbacks tutorial

---

.github/workflows/Deploy-internal.yml
.github/workflows/Deploy-website.yml

Trigger deploy on `Project.toml` modification

---

.github/workflows/Deploy-internal.yml
.github/workflows/Deploy-website.yml

- [NA] Tutorial name: NA
- #25
- [NA] Confirm that you have used a tool such as [Grammarly] to verify that the text is correct.
- [NA] The preview has your tutorial listed.
- [NA] The preview looks like what you want.
---
@tmigot, I think this should fix it.

Update MATRIX build to work when Project.toml is updated

---

.github/workflows/build_tutorial.sh

Update script to copy figures from tutorials/NAME/figures folder

---

tutorials/generic-adnlpmodels/Project.toml
tutorials/generic-adnlpmodels/index.jmd

Tutorial name: Multiprecision and genericity in NLPModels with automatic differentiation

Add tutorial for arbitrary precision in ADNLPModels

---

tutorials/generic-adnlpmodels/index.jmd

Remove title

---

tutorials/introduction-to-ripqp/index.jmd

Update title RipQP tutorial

---

src/JSOTutorials.jl

Add default `line_width`

---

tutorials/introduction-to-adnlpmodels/Project.toml

In particular, the print of models is fixed with this release.
Test #25

Bump to ADNLPModels 0.5

---

Project.toml
src/JSOTutorials.jl
src/pkg_list.jl
tutorials/introduction-to-linear-operators/index.jmd

This should make testing #62 and the resulting PRs from #61 easier.

Generate badges with versions from Pkg.status

---

tutorials/introduction-to-cannoles/index.jmd

Try debug CaNNoLeS tutorial

---

tutorials/introduction-to-ldlfactorizations/index.jmd

Following https://github.com/JuliaSmoothOptimizers/LDLFactorizations.jl/blob/main/docs/src/tutorial.md

Update LDLFactorizations tutorial

---

.github/workflows/build_tutorial.sh

- #
- It was discussed in some other manner. Follow-up of https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/pull/77

Copy files from `assets` folder

---

tutorials/introduction-to-quadraticmodels/assets/AFIRO.SIF
tutorials/introduction-to-quadraticmodels/index.jmd

Add AFIRO.sif in QM tutorial

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/Deploy-internal.yml
README.md
src/JSOTutorials.jl
tutorials/generic-adnlpmodels/index.jmd
tutorials/introduction-to-bundleadjustmentmodels/index.jmd
tutorials/introduction-to-cutest/index.jmd
tutorials/introduction-to-jsosolvers/index.jmd
tutorials/introduction-to-linear-operators/index.jmd
tutorials/introduction-to-pdenlpmodels/index.jmd
tutorials/introduction-to-quadraticmodels/index.jmd
tutorials/introduction-to-ripqp/index.jmd
tutorials/introduction-to-solverbenchmark/index.jmd

Update URL to use jso.dev

---

tutorials/advanced-jsosolvers/Project.toml
tutorials/advanced-jsosolvers/index.jmd

- https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/issues/20
[preview]: https://jso.dev/JSOTutorials.jl/

Add tutorial benchmarking subsolvers

---

.breakage/Project.toml
.breakage/get_jso_users.jl
.github/workflows/Breakage.yml
copier-answers.jso.yml

Automated update using JSOBestieTemplate

Update with JSOBestieTemplate for JSOTutorials
